server:
  port: 8084
spring:
  application:
    name: shipment-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/shipment-service
    username: sa
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true