server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/order-service
    username: sa
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true